[project]
name = "game-tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fasta2a>=0.5.0",
    "pydantic-ai>=1.0.10",
    "python-dotenv>=1.1.1",
]
